# Use the official Python image from the Docker Hub
FROM python:3.13.13

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the conatiner at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install flask

# Make PORT 5000 available to the world outside this container
EXPOSE 5000

# Run app.opy when the conatiner launches
CMD ["python","app.py"]